
import React,{useEffect,useState}from"react";
import{Plus,Upload,Trash2,Save,LogOut,Image as ImageIcon,Package,Globe}from"lucide-react";

type P={id:string;name:string;category:string;sku:string;price:number;originalPrice?:number;stock:number;shortDescription:string;description:string;images:string[];specifications:{label:string;value:string}[];featured:boolean;active:boolean;tags:string[]};
type S={brand:string;tagline:string;eyebrow:string;description:string;logo:string;banner:string;background:string;backgroundBlur:number;phone:string;whatsapp:string;facebook:string;instagram:string;tiktok:string;email:string;address:string};
type C={settings:S;products:P[]};
const empty:S={brand:"THIZ",tagline:"VALUE FOR YOUR EVERYDAY.",eyebrow:"Lifestyle • Everyday Essentials",description:"Thoughtfully selected products for modern daily life.",logo:"",banner:"",background:"",backgroundBlur:0,phone:"01600417212",whatsapp:"8801600417212",facebook:"",instagram:"",tiktok:"",email:"",address:"Bangladesh"};
const init:C={settings:empty,products:[]};
const money=(n:number)=>"৳"+Number(n||0).toLocaleString("en-BD");
async function getData(){try{let r=await fetch("/api");return r.ok?await r.json():init}catch{return init}}
export default function App(){
 const[cat,setCat]=useState<C>(init),[admin,setAdmin]=useState(location.pathname.startsWith("/admin"));
 useEffect(()=>{getData().then(x=>setCat({settings:{...empty,...x.settings},products:x.products||[]}))},[]);
 return admin?<Admin cat={cat} setCat={setCat} back={()=>{history.pushState({},"","/");setAdmin(false)}}/>:<Store cat={cat} admin={()=>{history.pushState({},"","/admin");setAdmin(true)}}/>
}
function Store({cat,admin}:{cat:C;admin:()=>void}){
 const[s]=useState(cat.settings),[search,setSearch]=useState(""),[sel,setSel]=useState<P|null>(null);
 const ps=cat.products.filter(p=>p.active&&(!search||p.name.toLowerCase().includes(search.toLowerCase())));
 const wa=(t:string)=>"https://wa.me/"+s.whatsapp+"?text="+encodeURIComponent(t);
 return <div className="min-h-screen bg-[#f6f6f2] text-black">
  {s.banner&&<div className="bg-black text-white text-center text-xs font-bold py-2">{s.banner}</div>}
  <header className="sticky top-0 z-30 bg-[#f6f6f2]/90 backdrop-blur-xl border-b border-black/10"><div className="max-w-7xl mx-auto px-6 h-20 flex items-center justify-between">
   {s.logo?<img src={s.logo} className="h-10 w-auto object-contain"/>:<b className="text-3xl tracking-[-.08em]">{s.brand}.</b>}
   <nav className="hidden md:flex gap-8 font-bold text-sm"><a href="#shop">Shop</a><a href="#about">About</a><a href="#contact">Contact</a></nav>
   <a href={wa("Hi THIZ, I want to order.")} target="_blank" className="rounded-full border border-black px-5 py-3 text-sm font-bold">Order on WhatsApp</a>
  </div></header>
  <section className="relative overflow-hidden"><img src={s.background||s.banner||""} className="absolute inset-0 w-full h-full object-cover opacity-20" style={{filter:"blur("+s.backgroundBlur+"px)"}}/><div className="relative max-w-7xl mx-auto px-6 py-24 grid lg:grid-cols-2 gap-12 items-center">
   <div><div className="uppercase tracking-[.22em] text-xs font-black text-[#666]">{s.eyebrow}</div><h1 className="text-[clamp(4rem,8vw,8rem)] leading-[.84] tracking-[-.075em] font-black mt-6">{s.tagline}</h1><p className="text-xl leading-8 text-[#666] max-w-xl mt-8">{s.description}</p><div className="flex gap-3 mt-8"><a href="#shop" className="bg-black text-white rounded-full px-6 py-4 font-bold">Explore products</a><a href={wa("Hi THIZ, I want to know more.")} target="_blank" className="border border-black/20 rounded-full px-6 py-4 font-bold">Talk to THIZ</a></div></div>
   <div className="min-h-[470px] rounded-[40px] overflow-hidden bg-gradient-to-br from-[#dce9df] to-[#f1e5d3]">{s.banner?<img src={s.banner} className="w-full h-full object-cover"/>:<div className="h-full grid place-items-center text-6xl font-black">{s.brand}</div>}</div>
  </div></section>
  <section id="shop" className="max-w-7xl mx-auto px-6 py-20"><div className="flex justify-between items-end gap-5 mb-8"><div><div className="uppercase tracking-[.2em] text-xs font-black text-[#666]">Collection</div><h2 className="text-5xl font-black tracking-[-.05em] mt-2">Made for daily life.</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search products…" className="bg-white border border-black/10 rounded-full px-5 py-3 w-64"/></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{ps.map(p=><article key={p.id} onClick={()=>setSel(p)} className="bg-white rounded-3xl p-3 border border-black/10 cursor-pointer hover:-translate-y-1 transition"><div className="aspect-square rounded-2xl overflow-hidden bg-[#e9ebe6]">{p.images[0]?<img src={p.images[0]} className="w-full h-full object-cover"/>:<div className="h-full grid place-items-center text-3xl font-black">{s.brand}</div>}</div><div className="p-4"><small className="uppercase tracking-widest text-[#777]">{p.category}</small><h3 className="text-xl font-black mt-2">{p.name}</h3><p className="text-sm text-[#666] mt-1">{p.shortDescription}</p><b className="block mt-4">{money(p.price)}</b></div></article>)}</div></section>
  <section id="about" className="max-w-7xl mx-auto px-6 py-20 grid md:grid-cols-2 gap-12"><h2 className="text-6xl font-black tracking-[-.06em]">Useful. Simple. Worth it.</h2><p className="text-xl leading-9 text-[#666]">THIZ focuses on practical lifestyle and everyday-use products, selected around real use, clean design and dependable value.</p></section>
  <section id="contact" className="max-w-7xl mx-auto px-6 py-20"><div className="bg-black text-white rounded-[36px] p-10 md:p-14"><div className="uppercase tracking-[.2em] text-xs font-black text-[#aaa]">Contact THIZ</div><h2 className="text-5xl font-black mt-3">Need something useful?</h2><p className="text-[#aaa] mt-4">Products, prices, availability and delivery information.</p><div className="flex gap-3 flex-wrap mt-8"><a href={wa("Hi THIZ, I want to place an order.")} target="_blank" className="border border-white/30 rounded-full px-5 py-3 font-bold">WhatsApp • {s.phone}</a>{s.facebook&&<a href={s.facebook} target="_blank" className="border border-white/30 rounded-full px-5 py-3">Facebook</a>}{s.instagram&&<a href={s.instagram} target="_blank" className="border border-white/30 rounded-full px-5 py-3">Instagram</a>}</div></div></section>
  <footer className="border-t border-black/10 max-w-7xl mx-auto px-6 py-10 flex justify-between"><b className="text-3xl">{s.brand}.</b><button onClick={admin} className="text-xs text-[#999]">Admin</button></footer>
  {sel&&<div className="fixed inset-0 z-50 bg-black/70 p-4 grid place-items-center" onClick={()=>setSel(null)}><div onClick={e=>e.stopPropagation()} className="bg-[#f6f6f2] max-w-5xl w-full max-h-[90vh] overflow-auto rounded-3xl p-6"><button onClick={()=>setSel(null)} className="float-right border rounded-full px-4 py-2">Close</button><div className="grid md:grid-cols-2 gap-8 clear-both"><div><img src={sel.images[0]} className="w-full aspect-square object-cover rounded-3xl"/><div className="flex gap-2 mt-3">{sel.images.slice(0,5).map((x,i)=><img key={i} src={x} className="w-20 h-20 object-cover rounded-xl"/>)}</div></div><div><small className="uppercase tracking-widest text-[#777]">{sel.category}</small><h2 className="text-5xl font-black mt-2">{sel.name}</h2><b className="text-2xl block mt-5">{money(sel.price)}</b><p className="text-[#666] leading-7 mt-5">{sel.description}</p><div className="mt-5">{sel.specifications.map((x,i)=><div key={i} className="flex justify-between border-b py-3"><b>{x.label}</b><span>{x.value}</span></div>)}</div><a href={wa("Hi THIZ, I want to order: "+sel.name+" SKU "+sel.sku)} target="_blank" className="inline-block mt-7 bg-black text-white rounded-full px-7 py-4 font-bold">Order this product</a></div></div></div></div>}
 </div>
}
function Admin({cat,setCat,back}:{cat:C;setCat:React.Dispatch<React.SetStateAction<C>>;back:()=>void}){
 const[logged,setLogged]=useState(false),[pass,setPass]=useState(""),[tab,setTab]=useState("products"),[edit,setEdit]=useState<P|null>(null),[msg,setMsg]=useState("");
 const save=async(c:C)=>{setCat(c);let r=await fetch("/api",{method:"POST",headers:{"content-type":"application/json","x-thiz-admin":pass},body:JSON.stringify({action:"saveCatalog",data:c})});setMsg(r.ok?"Saved":"Save failed: add THIZ_ADMIN_PASSWORD in Netlify.");};
 const upload=async(f:File,key:string)=>{let fd=new FormData();fd.append("file",f);fd.append("key",key);let r=await fetch("/api/upload",{method:"POST",headers:{"x-thiz-admin":pass},body:fd});if(!r.ok){setMsg("Upload failed. Configure THIZ_ADMIN_PASSWORD in Netlify.");return""}return(await r.json()).url};
 if(!logged)return <div className="min-h-screen bg-[#0b0c10] text-white grid place-items-center p-6"><div className="w-full max-w-md bg-[#15171d] border border-white/10 rounded-3xl p-8"><h1 className="text-3xl font-black">THIZ Admin</h1><p className="text-white/50 mt-2">Private business control center</p><input type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setLogged(pass==="thiz2026"||pass==="admin")} placeholder="Admin password" className="w-full mt-7 bg-black border border-white/10 rounded-xl px-4 py-3"/><button onClick={()=>setLogged(pass==="thiz2026"||pass==="admin")} className="w-full mt-3 bg-white text-black rounded-xl py-3 font-black">Sign in</button></div></div>;
 return <div className="min-h-screen bg-[#0b0c10] text-white"><header className="sticky top-0 z-20 bg-[#0b0c10]/90 backdrop-blur border-b border-white/10"><div className="max-w-7xl mx-auto h-20 px-5 flex justify-between items-center"><b className="text-2xl">THIZ Admin</b><div className="flex gap-2"><button onClick={back} className="bg-white/5 px-4 py-2 rounded-xl">Store</button><button onClick={()=>setLogged(false)} className="bg-white/5 p-2 rounded-xl"><LogOut size={17}/></button></div></div></header><main className="max-w-7xl mx-auto px-5 py-8"><div className="flex gap-2 mb-7 overflow-auto">{[["products","Products",Package],["appearance","Appearance",ImageIcon],["contacts","Contacts & Social",Globe]].map(([id,label,I]:any)=><button onClick={()=>setTab(id)} className={"px-5 py-3 rounded-xl font-bold whitespace-nowrap "+(tab===id?"bg-white text-black":"bg-white/5")}><I size={16} className="inline mr-2"/>{label}</button>)}</div>
 {tab==="products"&&<><div className="flex justify-between mb-6"><div><h1 className="text-3xl font-black">Products</h1><p className="text-white/50">Add details and up to 5 pictures.</p></div><button onClick={()=>setEdit({id:"thz-"+Date.now(),name:"",category:"Lifestyle",sku:"",price:0,stock:0,shortDescription:"",description:"",images:[],specifications:[{label:"Material",value:""},{label:"Color",value:""}],featured:false,active:true,tags:[]})} className="bg-white text-black px-5 py-3 rounded-xl font-black"><Plus className="inline" size={17}/> Add product</button></div><div className="grid md:grid-cols-3 gap-4">{cat.products.map(p=><div className="bg-[#15171d] border border-white/10 rounded-2xl p-3"><div className="aspect-video bg-black rounded-xl overflow-hidden">{p.images[0]&&<img src={p.images[0]} className="w-full h-full object-cover"/></div><div className="p-2"><b>{p.name||"Untitled"}</b><p className="text-white/50 text-sm">{money(p.price)} • Stock {p.stock}</p><button onClick={()=>setEdit(p)} className="mt-3 w-full bg-white/10 rounded-lg py-2">Edit</button></div></div>)}</div></>}
 {tab==="appearance"&&<Appearance cat={cat} setCat={setCat} save={save} upload={upload} msg={msg}/>}
 {tab==="contacts"&&<Contacts cat={cat} setCat={setCat} save={save} msg={msg}/>}
 </main>{edit&&<Editor product={edit} close={()=>setEdit(null)} save={p=>{let exists=cat.products.some(x=>x.id===p.id);save({...cat,products:exists?cat.products.map(x=>x.id===p.id?p:x):[p,...cat.products]});setEdit(null)}} upload={upload}/>}</div>
}
function Appearance({cat,setCat,save,upload,msg}:{cat:C;setCat:any;save:any;upload:any;msg:string}){const s=cat.settings;const set=(k:string,v:any)=>setCat((c:C)=>({...c,settings:{...c.settings,[k]:v}}));return <div className="max-w-3xl space-y-4"><h1 className="text-3xl font-black">Brand & Appearance</h1>{[["brand","Brand name"],["tagline","Hero headline"],["eyebrow","Eyebrow text"],["description","Hero description"]].map(([k,l])=><label className="grid gap-2"><b>{l}</b><input value={(s as any)[k]} onChange={e=>set(k,e.target.value)} className="bg-[#15171d] border border-white/10 rounded-xl px-4 py-3"/></label>)}{[["logo","Logo"],["banner","Banner / hero image"],["background","Background image"]].map(([k,l])=><Media key={k} label={l} value={(s as any)[k]} upload={upload} onChange={(v:string)=>set(k,v)}/>)}<label className="grid gap-2"><b>Background blur: {s.backgroundBlur}px</b><input type="range" min="0" max="30" value={s.backgroundBlur} onChange={e=>set("backgroundBlur",+e.target.value)}/></label><button onClick={()=>save(cat)} className="bg-white text-black rounded-xl px-6 py-3 font-black"><Save className="inline mr-2" size={16}/>Save appearance</button>{msg&&<p className="text-white/50">{msg}</p>}</div>}
function Contacts({cat,setCat,save,msg}:{cat:C;setCat:any;save:any;msg:string}){const s=cat.settings;const set=(k:string,v:any)=>setCat((c:C)=>({...c,settings:{...c.settings,[k]:v}}));return <div className="max-w-3xl space-y-4"><h1 className="text-3xl font-black">Contacts & Social</h1>{[["phone","Phone"],["whatsapp","WhatsApp number with country code"],["email","Email"],["address","Address"],["facebook","Facebook URL"],["instagram","Instagram URL"],["tiktok","TikTok URL"]].map(([k,l])=><label className="grid gap-2"><b>{l}</b><input value={(s as any)[k]} onChange={e=>set(k,e.target.value)} className="bg-[#15171d] border border-white/10 rounded-xl px-4 py-3"/></label>)}<button onClick={()=>save(cat)} className="bg-white text-black rounded-xl px-6 py-3 font-black"><Save className="inline mr-2" size={16}/>Save contacts</button>{msg&&<p className="text-white/50">{msg}</p>}</div>}
function Media({label,value,upload,onChange}:{label:string;value:string;upload:any;onChange:(v:string)=>void}){const[busy,setBusy]=useState(false);return <div className="bg-[#15171d] border border-white/10 rounded-2xl p-4"><b>{label}</b><div className="flex gap-4 items-center mt-3"><div className="w-28 h-20 bg-black rounded-xl overflow-hidden">{value&&<img src={value} className="w-full h-full object-contain"/>}</div><label className="bg-white/10 rounded-xl px-4 py-3 font-bold cursor-pointer">{busy?"Uploading…":<><Upload className="inline mr-2" size={16}/>Choose image</>}<input hidden type="file" accept="image/*" onChange={async e=>{let f=e.target.files?.[0];if(!f)return;setBusy(true);let u=await upload(f,"site-"+label.toLowerCase().replaceAll(" ","-"));if(u)onChange(u);setBusy(false)}}/></label></div></div>}
function Editor({product,close,save,upload}:{product:P;close:()=>void;save:(p:P)=>void;upload:any}){const[p,setP]=useState(product);const add=async(f:File)=>{if(p.images.length>=5)return;let u=await upload(f,"product-"+p.id+"-"+Date.now());if(u)setP(x=>({...x,images:[...x.images,u]}))};return <div className="fixed inset-0 z-50 bg-black/80 p-4 grid place-items-center"><div className="bg-[#15171d] border border-white/10 rounded-3xl max-w-4xl w-full max-h-[92vh] overflow-auto p-6"><div className="flex justify-between"><h2 className="text-2xl font-black">{p.name?"Edit":"Add"} product</h2><button onClick={close}>Close</button></div><div className="grid md:grid-cols-2 gap-4 mt-6">{[["name","Product name"],["category","Category"],["sku","SKU"],["price","Selling price"],["originalPrice","Original price"],["stock","Stock"],["shortDescription","Short description"]].map(([k,l])=><label className="grid gap-2"><b>{l}</b><input type={["price","originalPrice","stock"].includes(k)?"number":"text"} value={(p as any)[k]??""} onChange={e=>setP({...p,[k]:["price","originalPrice","stock"].includes(k)?+e.target.value:e.target.value})} className="bg-black border border-white/10 rounded-xl px-3 py-2"/></label>)}<label className="grid gap-2 md:col-span-2"><b>Full description</b><textarea rows={5} value={p.description} onChange={e=>setP({...p,description:e.target.value})} className="bg-black border border-white/10 rounded-xl px-3 py-2"/></label><div className="md:col-span-2"><b>Pictures ({p.images.length}/5)</b><div className="grid grid-cols-2 md:grid-cols-5 gap-3 mt-3">{p.images.map((x,i)=><div className="relative aspect-square rounded-xl overflow-hidden bg-black"><img src={x} className="w-full h-full object-cover"/><button onClick={()=>setP({...p,images:p.images.filter((_,j)=>j!==i)})} className="absolute top-2 right-2 bg-red-600 rounded-full p-1"><Trash2 size={13}/></button></div>)}{p.images.length<5&&<label className="aspect-square border border-dashed border-white/20 rounded-xl grid place-items-center cursor-pointer"><Plus/><input hidden type="file" accept="image/*" onChange={e=>{let f=e.target.files?.[0];if(f)add(f)}}/></label>}</div></div></div><div className="flex justify-end gap-3 mt-7"><button onClick={close} className="px-5 py-3 bg-white/5 rounded-xl">Cancel</button><button onClick={()=>save({...p,price:Number(p.price),stock:Number(p.stock),images:p.images.slice(0,5)})} className="px-6 py-3 bg-white text-black rounded-xl font-black"><Save className="inline mr-2" size={16}/>Save product</button></div></div></div>}
